#!/usr/bin/env bash

read -p "Revert $1? [y/N]: " -n 1 -r
echo

if [[ "$REPLY" =~ ^[Yy]$ ]]; then
    if [[ "$1" == "//..." ]]; then
        read -p "Really? [y/N]: " -n 1 -r
        echo
        if ! [[ "$REPLY" =~ ^[Yy]$ ]]; then
            echo "Cancelling"
            exit 1
        fi
    fi
    p4 revert "$1" || echo 'Error reverting'
else
    echo "Cancelling"
fi
