#!/usr/bin/env python
import copy, sys
from pyPdf import PdfFileWriter, PdfFileReader
input = PdfFileReader(sys.stdin)
output = PdfFileWriter()
for p in [input.getPage(i) for i in range(0,input.getNumPages())]:
    q, r, s = (copy.copy(p) for i in range(3))
    (w, h) = p.mediaBox.upperRight
    p.mediaBox.lowerRight = (w/2, h/2)
    q.mediaBox.lowerLeft = (w/2, h/2)
    r.mediaBox.upperRight = (w/2, h/2)
    s.mediaBox.upperLeft = (w/2, h/2)
    for i in p, q, r, s:
        output.addPage(i)
output.write(sys.stdout)

