#!/bin/env bash

FILE_NAME="$1"


compile_latex() {
    pdflatex -interaction=nonstopmode --output-directory ./build "$FILE_NAME"
}

generate_bibliography() {
(cd build && cp ../${FILE_NAME/.tex/.bib} ./ && bibtex ${FILE_NAME/.tex/})
}

mkdir -p build

while watch-file "$FILE_NAME"; do
    compile_latex > /dev/null && generate_bibliography;
    compile_latex
done
