#!/bin/env bash

FILE_NAME="$1"


compile_latex() {
    pdflatex -interaction=nonstopmode --output-directory ./build "$FILE_NAME"
}

generate_bibliography() {
    (cd build && cp ../*.bib ./ && bibtex ${FILE_NAME/.tex/} )
}

compile_with_bibliography() {
    compile_latex > /dev/null && generate_bibliography;
    compile_latex > /dev/null
    compile_latex
}

init() {
    if test -z "$(shopt -s nullglob; echo *.bib)"
    then
        touch ${FILE_NAME/.tex/.bib}
    fi
    mkdir -p build
    compile_with_bibliography
    evince ./build/${FILE_NAME/.tex/.pdf} >/dev/null 2>&1 &
}

init

while watch-file "$FILE_NAME"; do
    compile_with_bibliography
done
