#!/bin/bash

# force parameter
if [[ "$1" != "-y" && "$2" != "-y" ]]
then
    # confirm with user
    read -p 'Power down [y/n]? ' -n1 -r
    # print empty line
    echo
    if [[ ! "$REPLY" =~ ^[Yy]$ ]]
    then
        echo Cancelling
        exit 1
    fi
fi

echo "Powering down VMs"

qvm-shutdown --wait --all

if [[ "$1" != "-n" && "$2" != "-n" ]]
then
    echo "Halting system"
    systemctl poweroff
fi
