#!/bin/bash

# force parameter
if [[ "$1" != "-y" && "$2" != "-y" ]]
then
    # confirm with user
    read -p 'Power down [y/n]? ' -n1 -r
    # print empty line
    echo
    if [[ ! "$REPLY" =~ ^[Yy]$ ]]
    then
        echo Cancelling
        exit 1
    fi
fi

if [[ "$1" == "-n" || "$2" == "-n" ]]
then
    echo "This option has been deprecated. Aborting."
    exit 1
fi

echo "Powering down VMs"

qvm-shutdown --wait --all

systemctl poweroff
