#!/usr/bin/env bash

shopt -s expand_aliases

RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
RESET=$(tput sgr0)
CLEAR=$(tput el)

HALTED='"Halted"'
ZERO='$0'
TWO='$2'

alias cmd="qvm-ls --no-spinner -O NAME,STATE,TEMPLATE,CLASS,NETVM"

# Header for use in filtered output (which doesn't include header)
HEADER=$(cmd | head -1)

### HELPERS THAT NEED WRAPPING ###

# Only list running and transient. Unused as of the writing of this comment
# TODO: add switch for using this
alias filteredcmd="cmd | awk '$TWO!=$HALTED {print $ZERO};'"

alias colour=" \
	sed ' \
	s/^sys-firewall.*/${MAGENTA}\0${RESET}/; \
	s/.*Running/${GREEN}\0${RESET}/; \
	s/.*Transient/${RED}\0${RESET}/; \
	s/.*Dying/${RED}\0${RESET}/; \
'"

# I don't understand the dumpster fire that is sort, but this weems to work
# For some reason, I need to refer to the second field as 3, and I need
# to change the LOCALE for it to handle spaces properly. There should
# be a sane_sort program ...
alias sortedcmd="filteredcmd | tail -n +2 | LC_ALL=POSIX sort -s -k3,3r"

colourcmd () {
	# Move to top left
	tput cup 0 0 
	date 
	echo "$HEADER" 
	sortedcmd | colour
}

# highlight i-th column
highlight_col () {
	local prog='{for (i=1 ; i <= NR ; i++){printf "%s ", $i}}'
	awk "$prog" -
}

### WRAPPER FOR HELPERS ###

main () {
	# Flickers without this
	new="$(colourcmd)"
	new="${new}\n$(printf '%250s' | tr ' ' =)"
	new="${new}\n$(psgrep qvm-run)"
	printf "$new$(tput ed)" | sed "s/$/$CLEAR/;"
	
}

### OUTPUT STARTS HERE ###

tput clear

# Hide cursor
tput civis

# Don't wrap long lines
tput rmam

# Restore cursor
trap "tput cvvis; tput smam" SIGINT SIGTERM

main
while sleep 5; do
	main
done
